//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SharedModule } from '@src/app/shared/shared.module';
import { LayoutModule } from '@progress/kendo-angular-layout';
import { MainSiteModuleComponent } from '@src/app/modules/main-site/main-site.component';
import { MainSiteRoutingModule } from '@src/app/modules/main-site/main-site-routing.module';
import { AppLayoutViewModule } from '@src/app/modules/system/app-layout/app-layout.module';
import { WrapperViewModule } from '@src/app/modules/main-site/wrapper/wrapper.module';

import { config, transformConfig } from '@src/app/modules/main-site/main-site.config';

const configMeta: NgModule = {
    providers: [...config.providers],
    declarations: [MainSiteModuleComponent, ...config.declarations],
    imports: [CommonModule, SharedModule, LayoutModule, AppLayoutViewModule, WrapperViewModule, MainSiteRoutingModule, ...config.imports],
    exports: [...config.exports],
    entryComponents: [...config.entryComponents],
    bootstrap: [...config.bootstrap],
    schemas: [...config.schemas],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class MainSiteModule {}
