//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the quick-claim-simple.config.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutModule } from '@progress/kendo-angular-layout';
import { SharedModule } from '@src/app/shared/shared.module';
import { QuickClaimSimpleViewBaseComponent } from '@src/app/modules/claims/quick-claim-simple/quick-claim-simple.base.component';
import { QuickClaimSimpleViewComponent } from '@src/app/modules/claims/quick-claim-simple/quick-claim-simple.component';
import { RouterModule } from '@angular/router';

import { BottomSectionComponent } from '@src/app/modules/claims/quick-claim-simple/bottom-section.component';
import { MiddleSectionComponent } from '@src/app/modules/claims/quick-claim-simple/middle-section.component';
import { TopSectionComponent } from '@src/app/modules/claims/quick-claim-simple/top-section.component';

import { config, transformConfig } from '@src/app/modules/claims/quick-claim-simple/quick-claim-simple.config';

const configMeta: NgModule = {
    providers: [...config.providers],
    declarations: [
        QuickClaimSimpleViewBaseComponent,
        QuickClaimSimpleViewComponent,
        BottomSectionComponent,
        MiddleSectionComponent,
        TopSectionComponent,
        ...config.declarations
    ],
    imports: [CommonModule, SharedModule, LayoutModule, RouterModule, ...config.imports],
    exports: [BottomSectionComponent, MiddleSectionComponent, TopSectionComponent, ...config.exports],
    entryComponents: [...config.entryComponents],
    bootstrap: [...config.bootstrap],
    schemas: [...config.schemas],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class QuickClaimSimpleViewModule {}
