//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes } from '@angular/router';
import { NativeScriptRouterModule, NSEmptyOutletComponent } from 'nativescript-angular/router';
import { AuthenticationGuardService } from '@src/app/core/auth/authentication-guard.service';
import { AppTabsComponent } from '@src/app/app-tabs.component';

import * as routeConfig from '@src/app/app-routing.config';

export const defaultRoute = '_app';

const routes: Routes = [
    { path: '', redirectTo: defaultRoute, pathMatch: 'full' },
    {
        path: defaultRoute,
        data: { enableDrawer: true },
        component: AppTabsComponent,
        canActivate: [AuthenticationGuardService],
        canActivateChild: [AuthenticationGuardService],
        children: [
            {
                path: 'system',
                outlet: 'systemHomeTab',
                component: NSEmptyOutletComponent,
                loadChildren: '@src/app/modules/system/system.module#SystemModule'
            }
        ]
    },
    {
        path: 'system',
        loadChildren: '@src/app/modules/system/system.module#SystemModule'
    },
    {
        path: 'claims',
        loadChildren: '@src/app/modules/claims/claims.module#ClaimsModule'
    },
    {
        path: 'policies',
        loadChildren: '@src/app/modules/policies/policies.module#PoliciesModule'
    },
    {
        path: 'main-site',
        loadChildren: '@src/app/modules/main-site/main-site.module#MainSiteModule'
    },
    ...routeConfig.config.routes
];

((routeConfig as any).transformRoutes || (routes => {}))(routes);

@NgModule({
    imports: [NativeScriptRouterModule.forRoot(routes, (<any>routeConfig.config).extraOptions)],
    exports: [NativeScriptRouterModule]
})
export class AppRoutingModule {}
