//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the quick-claim.component.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, ViewEncapsulation, OnInit, AfterViewInit, OnDestroy, Injector } from '@angular/core';

import { ActivatedRoute } from '@angular/router';
import { map } from 'rxjs/operators';

import { UtilsService } from '@src/app/core/services/utils.service';
import { DataServiceFactory } from '@src/app/core/data/data-service.factory';
import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { CollectionDataService } from '@src/app/core/data/collection-data.service';
import { CollectionState } from '@src/app/core/data/state/collection-state.interface';
import { Claim } from '@src/app/data/claim.model';
import { Policy } from '@src/app/data/policy.model';
import { getClaimConfig } from '@src/app/data/claim.config';
import { getPolicyConfig } from '@src/app/data/policy.config';
import { ErrorHandlingService } from '@src/app/core/error-handling.service';

@Component({
    templateUrl: './quick-claim.component.html',
    styleUrls: ['./quick-claim.component.css']
})
export class QuickClaimViewBaseComponent implements OnInit, AfterViewInit, OnDestroy {
    public $config = {
        components: {
            tabstrip0: {},
            label3: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label3.text'
            },
            label0: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label0.text'
            },
            booleanradiobuttonlist0: {
                value: false,
                trueTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.booleanradiobuttonlist0.trueText',
                falseTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.booleanradiobuttonlist0.falseText'
            },
            iWarning: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.iWarning.text'
            },
            label1: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label1.text'
            },
            booleanradiobuttonlist1: {
                value: false,
                trueTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.booleanradiobuttonlist1.trueText',
                falseTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.booleanradiobuttonlist1.falseText'
            },
            vWarning: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.vWarning.text'
            },
            label4: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label4.text'
            },
            label5: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label5.text'
            },
            policy: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.policy.placeholder',
                name: 'policybox',
                value: '',
                title: '',
                debounce: 0
            },
            label6: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label6.text'
            },
            datepicker0: {
                format: 'M/d/yyyy',
                title: '',
                min: new Date('1899-12-31T22:00:00.000Z'),
                max: new Date('2099-12-30T22:00:00.000Z')
            },
            label7: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.label7.text'
            },
            timepicker0: {
                format: 'H:mm',
                title: '',
                steps: { hour: 1, minute: 30, second: 1 }
            },
            button0: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.button0.content'
            },
            button1: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.91dd00fe-8974-401b-a76e-e3826185925f.components.button1.content'
            },
            label8: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label8.text'
            },
            label9: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label9.text'
            },
            label19: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label19.text'
            },
            combobox1: {
                title: '',
                textField: '',
                valueField: '',
                valuePrimitive: false,
                filterable: true,
                filter: 'Contains',
                clientFiltering: false
            },

            label10: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label10.text'
            },
            textarea0: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textarea0.placeholder',
                name: 'textarea0',
                value: '',
                title: '',
                debounce: 0
            },
            label11: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label11.text'
            },
            label12: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label12.text'
            },
            textbox1: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textbox1.placeholder',
                name: 'textbox1',
                value: '',
                title: '',
                debounce: 0
            },
            textbox2: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textbox2.placeholder',
                name: 'textbox2',
                value: '',
                title: '',
                debounce: 0
            },
            label14: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label14.text'
            },
            textbox3: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textbox3.placeholder',
                name: 'textbox3',
                value: '',
                title: '',
                debounce: 0
            },
            label15: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label15.text'
            },
            textbox4: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textbox4.placeholder',
                name: 'textbox4',
                value: '',
                title: '',
                debounce: 0
            },
            label16: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label16.text'
            },
            combobox0: {
                title: '',
                textField: '',
                valueField: '',
                valuePrimitive: false,
                filterable: false,
                filter: 'StartsWith',
                clientFiltering: true
            },

            label17: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label17.text'
            },
            textbox6: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textbox6.placeholder',
                name: 'textbox6',
                value: '',
                title: '',
                debounce: 0
            },
            label18: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.label18.text'
            },
            textbox5: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.textbox5.placeholder',
                name: 'textbox5',
                value: '',
                title: '',
                debounce: 0
            },
            button2: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.button2.content'
            },
            button3: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.678b195b-98c7-47a0-b7ae-1d96d552c4ba.components.button3.content'
            },
            label13: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label13.text'
            },
            label20: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label20.text'
            },
            textbox7: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox7.placeholder',
                name: 'textbox7',
                value: '',
                title: '',
                debounce: 0
            },
            label21: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label21.text'
            },
            textbox8: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox8.placeholder',
                name: 'textbox8',
                value: '',
                title: '',
                debounce: 0
            },
            label22: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label22.text'
            },
            textbox9: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox9.placeholder',
                name: 'textbox9',
                value: '',
                title: '',
                debounce: 0
            },
            label23: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label23.text'
            },
            textbox10: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox10.placeholder',
                name: 'textbox10',
                value: '',
                title: '',
                debounce: 0
            },
            label24: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label24.text'
            },
            label39: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label39.text'
            },
            textbox11: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox11.placeholder',
                name: 'textbox11',
                value: '',
                title: '',
                debounce: 0
            },
            label25: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label25.text'
            },
            combobox2: {
                title: '',
                textField: '',
                valueField: '',
                valuePrimitive: false,
                filterable: false,
                filter: 'StartsWith',
                clientFiltering: true
            },

            label26: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label26.text'
            },
            phonetextbox0: {
                title: '',
                mask: '(999) 000-0000',
                value: ''
            },
            label27: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label27.text'
            },
            phonetextbox1: {
                title: '',
                mask: '(999) 000-0000',
                value: ''
            },
            label28: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label28.text'
            },
            emailtextbox0: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.emailtextbox0.placeholder',
                name: 'emailtextbox0',
                value: '',
                title: '',
                debounce: 0
            },
            label29: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label29.text'
            },
            combobox3: {
                title: '',
                textField: '',
                valueField: '',
                valuePrimitive: true,
                filterable: false,
                filter: 'StartsWith',
                clientFiltering: true
            },

            label30: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label30.text'
            },
            label31: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label31.text'
            },
            label65: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label65.text'
            },
            booleanradiobuttonlist2: {
                value: true,
                trueTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.booleanradiobuttonlist2.trueText',
                falseTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.booleanradiobuttonlist2.falseText'
            },
            label32: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label32.text'
            },
            textbox12: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox12.placeholder',
                name: 'textbox12',
                value: '',
                title: '',
                debounce: 0
            },
            label33: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label33.text'
            },
            textbox13: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox13.placeholder',
                name: 'textbox13',
                value: '',
                title: '',
                debounce: 0
            },
            label34: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label34.text'
            },
            textbox14: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox14.placeholder',
                name: 'textbox14',
                value: '',
                title: '',
                debounce: 0
            },
            label35: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label35.text'
            },
            textbox15: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox15.placeholder',
                name: 'textbox15',
                value: '',
                title: '',
                debounce: 0
            },
            label36: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label36.text'
            },
            label40: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label40.text'
            },
            textbox16: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox16.placeholder',
                name: 'textbox16',
                value: '',
                title: '',
                debounce: 0
            },
            label37: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label37.text'
            },
            textbox17: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.textbox17.placeholder',
                name: 'textbox17',
                value: '',
                title: '',
                debounce: 0
            },
            label38: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label38.text'
            },
            label66: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.label66.text'
            },
            booleanradiobuttonlist3: {
                value: true,
                trueTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.booleanradiobuttonlist3.trueText',
                falseTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.booleanradiobuttonlist3.falseText'
            },
            button4: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.button4.content'
            },
            button5: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e8493f8c-6736-480d-acfe-d3536bce29db.components.button5.content'
            },
            label41: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label41.text'
            },
            label42: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label42.text'
            },
            textbox18: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox18.placeholder',
                name: 'textbox18',
                value: '',
                title: '',
                debounce: 0
            },
            label43: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label43.text'
            },
            textbox19: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox19.placeholder',
                name: 'textbox19',
                value: '',
                title: '',
                debounce: 0
            },
            label44: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label44.text'
            },
            textbox20: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox20.placeholder',
                name: 'textbox20',
                value: '',
                title: '',
                debounce: 0
            },
            label45: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label45.text'
            },
            textbox21: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox21.placeholder',
                name: 'textbox21',
                value: '',
                title: '',
                debounce: 0
            },
            label46: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label46.text'
            },
            label64: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label64.text'
            },
            textbox22: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox22.placeholder',
                name: 'textbox22',
                value: '',
                title: '',
                debounce: 0
            },
            label47: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label47.text'
            },
            textbox23: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox23.placeholder',
                name: 'textbox23',
                value: '',
                title: '',
                debounce: 0
            },
            label48: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label48.text'
            },
            phonetextbox2: {
                title: '',
                mask: '(999) 000-0000',
                value: ''
            },
            label49: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label49.text'
            },
            phonetextbox3: {
                title: '',
                mask: '(999) 000-0000',
                value: ''
            },
            label50: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label50.text'
            },
            emailtextbox1: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.emailtextbox1.placeholder',
                name: 'emailtextbox1',
                value: '',
                title: '',
                debounce: 0
            },
            label51: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label51.text'
            },
            combobox4: {
                title: '',
                textField: '',
                valueField: '',
                valuePrimitive: false,
                filterable: false,
                filter: 'StartsWith',
                clientFiltering: true
            },

            label52: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label52.text'
            },
            label53: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label53.text'
            },
            label61: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label61.text'
            },
            booleanradiobuttonlist4: {
                value: false,
                trueTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.booleanradiobuttonlist4.trueText',
                falseTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.booleanradiobuttonlist4.falseText'
            },
            label54: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label54.text'
            },
            textbox24: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox24.placeholder',
                name: 'textbox24',
                value: '',
                title: '',
                debounce: 0
            },
            label55: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label55.text'
            },
            textbox25: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox25.placeholder',
                name: 'textbox25',
                value: '',
                title: '',
                debounce: 0
            },
            label56: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label56.text'
            },
            textbox26: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox26.placeholder',
                name: 'textbox26',
                value: '',
                title: '',
                debounce: 0
            },
            label57: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label57.text'
            },
            textbox27: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox27.placeholder',
                name: 'textbox27',
                value: '',
                title: '',
                debounce: 0
            },
            label58: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label58.text'
            },
            label63: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label63.text'
            },
            textbox28: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox28.placeholder',
                name: 'textbox28',
                value: '',
                title: '',
                debounce: 0
            },
            label59: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label59.text'
            },
            textbox29: {
                placeholderKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.textbox29.placeholder',
                name: 'textbox29',
                value: '',
                title: '',
                debounce: 0
            },
            label60: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label60.text'
            },
            label62: {
                forAttribute: '',
                textKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.label62.text'
            },
            booleanradiobuttonlist5: {
                value: true,
                trueTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.booleanradiobuttonlist5.trueText',
                falseTextKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.booleanradiobuttonlist5.falseText'
            },
            button6: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.button6.content'
            },
            button7: {
                primary: false,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.c182b786-3efb-43cb-a524-3abfeb32bc24.components.button7.content'
            },
            button8: {
                primary: true,
                icon: '',
                contentKey:
                    'modules.Claims.views.QuickClaim.components.tabstrip0.items.e0836b6e-8021-4a94-bb30-b7a013db9a9b.components.button8.content'
            },
            customhtml0: {}
        }
    };

    public $viewDataSource1Service: CollectionDataService<Claim>;
    public $viewDataSource2Service: CollectionDataService<Policy>;

    public $dataModels: any = {
        ViewDataSource1Model: {},
        ViewDataSource2Model: {}
    };

    protected $activatedRoute: ActivatedRoute;
    protected $utilsService: UtilsService;
    protected $serviceFactory: DataServiceFactory;
    protected $errorHandlingService: ErrorHandlingService;

    constructor(public injector: Injector) {
        this.$activatedRoute = injector.get(ActivatedRoute);
        this.$utilsService = injector.get(UtilsService);
        this.$serviceFactory = injector.get(DataServiceFactory);
        this.$errorHandlingService = injector.get(ErrorHandlingService);

        const dataConfig = {
            viewDataSource1: getClaimConfig(),
            viewDataSource2: getPolicyConfig()
        };

        this.initDataServices(dataConfig);
    }

    public ngOnInit(): void {
        this['onInit']();
    }

    public ngAfterViewInit(): void {
        this['onShow']();
    }

    public ngOnDestroy(): void {
        this['onHide']();
    }

    protected initDataServices(dataConfig: { [key: string]: KinveyServiceConfig }) {
        this.$viewDataSource1Service = this.$serviceFactory.collection<Claim>({
            config: dataConfig.viewDataSource1,
            initialState: {
                skip: 0,
                take: 20
            },
            typeName: Claim.name
        });

        this.$viewDataSource2Service = this.$serviceFactory.collection<Policy>({
            config: dataConfig.viewDataSource2,
            initialState: {
                skip: 0,
                take: 20
            },
            typeName: Policy.name
        });

        this.$errorHandlingService.subscribe(this.$viewDataSource1Service.errors);
        this.$errorHandlingService.subscribe(this.$viewDataSource2Service.errors);
    }
}
